server:
  port: 8881

eureka:
  client:
    service-url:
      # 多个注册中心使用','分割
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    metadata-map:
#      version: dev

spring:
  application:
    name: order-service

feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 3000
#        requestInterceptors:
#          - com.sm.finchley.loadbalance.interceptor.FeignRequestInterceptor
