server:
  port: 8883

eureka:
  client:
    service-url:
      # 多个注册中心使用','分割
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: dev
spring:
  application:
    name: user-service
  data:
    elasticsearch:
      cluster-nodes: localhost:9200

feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 3000
