eureka:
  client:
    service-url:
      # 多个注册中心使用','分割
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
      globalcors:
        cors-configurations[/**]:
          allowed-origin-patterns: "*"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
          max-age: 18000
      routes:
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1 # 移除前缀
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1 # 移除前缀
management:
  endpoints:
    web:
      exposure:
        include: "*"


