server:
  port: 8882

eureka:
  client:
    service-url:
      # 多个注册中心使用','分割
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: storage-service

feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 3000
